### ISSUE TITLE
Asynchronous inserts may generate IDs not always sequential for different tables on different shards

### ISSUE THREAD

**Issue by alfredbaudisch** [alfredbaudisch/ecto_instashard#1]
This is somewhat obvious, but it is worth noting: stress tests have shown that under high concurrency, an INSERT command that comes after another sometimes may be inserted first and have a lower Id than the first INSERT.

Example:

``` sql
TABLE: shard31.messages, Entry ID: 1234
TABLE: shard1024.uploads, Entry ID: 1233
```

This happens only on different tables across different shards, so for most use cases that is not a problem. Normally just a single table is sharded, so this is a special case.
# Alternative 1: Single table

If it is desired to shard multiple tables with sequential IDs, it is recommended to structure a single table that support data in a generic way for the multiple needs with a JSONB column, i.e. 

``` sql
CREATE TABLE shard$1.data (
  id bigint not null default shard$1.next_id(),
  data jsonb,
  inserted_at timestamp with time zone default now() not null,
  PRIMARY KEY(id)
);
```
# Alternative 2: Batch Inserts!

Batch Inserts! Not much to explain here :D.
# Failed test

``` elixir
  * test Sharding ids are sequential for different tables and users (1293.1ms)

  1) test Sharding ids are sequential for different tables and users (Fred.Data.Messages)
     test/messages_test.exs:93
     Assertion with < failed
     code: bot_data_id < upload_id

     lhs:  1370600047435076597
     rhs:  1370600047435058026
     stacktrace:
       test/messages_test.exs:130: anonymous fn/2 in Fred.Data.Messages.test Sharding ids are sequential for different tables and users/1
       (elixir) lib/enum.ex:1628: anonymous fn/3 in Enum.reduce/3
       (elixir) lib/range.ex:92: Enumerable.Range.reduce/5
       (elixir) lib/enum.ex:1627: Enum.reduce/3
       test/messages_test.exs:94: (test)
```

**Comment by alfredbaudisch** [comment]
Keeping this open, in case this very special use case is necessary.

**Comment by alfredbaudisch** [comment]
Each table should have its own `next_id` function anyway, it's what we have been done in production for many years without any issues. Closing this, after 4 years.
